n = input('digite algo')
print(type(n))
print('só tem espaços?', n.isspace())
print('é alfabetico?', n.isalpha())
print('é numero?', n.isnumeric())
print('é alfanumerico?', n.isalnum())
print('é só maiusculas?', n.isupper())
print('é só minusculas?', n.islower())
print('está capitalizado?', n.istitle())