nome = input('Digite seu nome: ')
dividido = nome.split()
print(f'Seu nome em maiúsculas: {nome.upper()}')
print(f'Seu nome em minúsculas: {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(' ')} letras')
print(f'Seu primeiro nome é {dividido[0].capitalize()} e ele tem {len(dividido[0])} letras')